### ISSUE TITLE
[Bug] Game crashes when trying to view a structure in REI

### ISSUE THREAD

**Issue by vizthex123** [ticticboooomer/MasterfulMachinery#66] opened 2024-05-22 22:08 UTC
# Version Information
**Forge version:** 47.2.6
**Masterful Machinery version:** 0.1.5
**Minecraft:** 1.20.1

## Add-Ons
None installed

# Further Information
[Log](https://gist.github.com/vizthex123/d2f671258a296933e8686cbe80018ebe)

I found out it's because I was using an invalid block tag. Would be nice if the mod warned you in-game or didn't load the file if it detects invalid block tags.

_**Update**: Happened again after I fixed the block tags. Never happened until I swapped to block tags._

[Log 2](https://gist.github.com/vizthex123/c20fa498233f1e4061d5931afee296ba)

**Comment by vizthex123** [comment] 2024-05-23 01:06
Update: It happened after I fixed the block tag.

Log:
[latest.log](https://github.com/ticticboooomer/MasterfulMachinery/files/15410192/latest.log)

**Comment by vizthex123** [comment] 2024-05-25 22:44
Update 2: Seems like this is being caused by me trying to use custom block tags in my structures. I'm using KubeJS to add them, so maybe that's the cause? Maybe it's trying to render a tag that hasn't the game hasn't registered yet or something?

Either way, here's the script that adds the tags and my new game log:
[script-and-log.zip](https://github.com/ticticboooomer/MasterfulMachinery/files/15445281/script-and-log.zip)

**Comment by ticticboooomer** [comment] 2024-05-26 10:39
closing, im certain this is not a bug, this should be discussed in discord

**Closed by ticticboooomer** 2024-05-26 10:39 UTC
Labels: bug
